### ISSUE TITLE
Error installing redis-stack on mac M1

### ISSUE THREAD

**Issue by GabrielGric** [redis-stack/homebrew-redis-stack#51]
When running this command: brew install redis-stack got this:

==> Installing Cask redis-stack-server
==> Purging files for version 7.2.0-v10 of Cask redis-stack-server
Error: undefined method `exists?' for class Dir

**Comment by john-ju** [comment]
found a fix in an older issue

https://github.com/redis-stack/homebrew-redis-stack/issues/45#issuecomment-2148449328

**Comment by GabrielGric** [comment]
Solved it.
